/** @type {import('tailwindcss').Config} */
import tokens from './design_tokens.json' assert { type: 'json' };

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: tokens.colors.primary,
        'on-primary': tokens.colors['on-primary'],
        'primary-light': tokens.colors['primary-light'],
        'primary-dark': tokens.colors['primary-dark'],
        secondary: tokens.colors.secondary,
        'on-secondary': tokens.colors['on-secondary'],
        tertiary: tokens.colors.tertiary,
        'on-tertiary': tokens.colors['on-tertiary'],
        'tertiary-light': tokens.colors['tertiary-light'],
        'tertiary-dark': tokens.colors['tertiary-dark'],
        background: tokens.colors.background,
        surface: tokens.colors.surface,
        'surface-elevated': tokens.colors['surface-elevated'],
        'surface-muted': tokens.colors['surface-muted'],
        'surface-secondary': tokens.colors['surface-secondary'],
        'on-surface': tokens.colors['on-surface'],
        'on-surface-variant': tokens.colors['on-surface-variant'],
        'on-surface-muted': tokens.colors['on-surface-muted'],
        outline: tokens.colors.outline,
        'outline-variant': tokens.colors['outline-variant'],
        'outline-focused': tokens.colors['outline-focused'],
        accent: tokens.colors.accent,
        'accent-light': tokens.colors['accent-light'],
        'accent-dark': tokens.colors['accent-dark'],
        'accent-bg': tokens.colors['accent-bg'],
        success: tokens.colors.success,
        'success-light': tokens.colors['success-light'],
        'success-bg': tokens.colors['success-bg'],
        warning: tokens.colors.warning,
        'warning-light': tokens.colors['warning-light'],
        'warning-bg': tokens.colors['warning-bg'],
        error: tokens.colors.error,
        'error-light': tokens.colors['error-light'],
        'error-bg': tokens.colors['error-bg'],
        info: tokens.colors.info,
        'info-light': tokens.colors['info-light'],
        'info-bg': tokens.colors['info-bg'],
        'purple-light': tokens.colors['purple-light'],
        'purple-accent': tokens.colors['purple-accent'],
        'purple-bg': tokens.colors['purple-bg'],
        panel: tokens.colors.panel,
        card: tokens.colors.card,
        hover: tokens.colors.hover,
        'hover-secondary': tokens.colors['hover-secondary'],
        muted: tokens.colors.muted,
        'text-primary': tokens.colors['text-primary'],
        'text-secondary': tokens.colors['text-secondary'],
        'text-muted': tokens.colors['text-muted'],
        'text-disabled': tokens.colors['text-disabled'],
        canvas: {
          bg: tokens.colors.canvas.bg,
          grid: tokens.colors.canvas.grid,
          node: tokens.colors.canvas.node,
          'node-hover': tokens.colors.canvas['node-hover'],
          accent: tokens.colors.canvas.accent,
          text: tokens.colors.canvas.text,
        },
      },
      fontFamily: {
        sans: ['PingFang SC', 'Microsoft YaHei', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
      },
      fontSize: {
        'display-xl': [tokens.typography['display-xl'].fontSize, {
          fontWeight: tokens.typography['display-xl'].fontWeight,
          lineHeight: tokens.typography['display-xl'].lineHeight,
          letterSpacing: tokens.typography['display-xl'].letterSpacing,
        }],
        'display-lg': [tokens.typography['display-lg'].fontSize, {
          fontWeight: tokens.typography['display-lg'].fontWeight,
          lineHeight: tokens.typography['display-lg'].lineHeight,
          letterSpacing: tokens.typography['display-lg'].letterSpacing,
        }],
        'headline-xl': [tokens.typography['headline-xl'].fontSize, {
          fontWeight: tokens.typography['headline-xl'].fontWeight,
          lineHeight: tokens.typography['headline-xl'].lineHeight,
        }],
        'headline-lg': [tokens.typography['headline-lg'].fontSize, {
          fontWeight: tokens.typography['headline-lg'].fontWeight,
          lineHeight: tokens.typography['headline-lg'].lineHeight,
        }],
        'headline-md': [tokens.typography['headline-md'].fontSize, {
          fontWeight: tokens.typography['headline-md'].fontWeight,
          lineHeight: tokens.typography['headline-md'].lineHeight,
        }],
        'title-lg': [tokens.typography['title-lg'].fontSize, {
          fontWeight: tokens.typography['title-lg'].fontWeight,
          lineHeight: tokens.typography['title-lg'].lineHeight,
        }],
        'title-md': [tokens.typography['title-md'].fontSize, {
          fontWeight: tokens.typography['title-md'].fontWeight,
          lineHeight: tokens.typography['title-md'].lineHeight,
        }],
        'body-lg': [tokens.typography['body-lg'].fontSize, {
          fontWeight: tokens.typography['body-lg'].fontWeight,
          lineHeight: tokens.typography['body-lg'].lineHeight,
        }],
        'body-md': [tokens.typography['body-md'].fontSize, {
          fontWeight: tokens.typography['body-md'].fontWeight,
          lineHeight: tokens.typography['body-md'].lineHeight,
        }],
        'body-sm': [tokens.typography['body-sm'].fontSize, {
          fontWeight: tokens.typography['body-sm'].fontWeight,
          lineHeight: tokens.typography['body-sm'].lineHeight,
        }],
        'body-xs': ['11px', {
          fontWeight: '400',
          lineHeight: '16px',
        }],
        'label-lg': [tokens.typography['label-lg'].fontSize, {
          fontWeight: tokens.typography['label-lg'].fontWeight,
          lineHeight: tokens.typography['label-lg'].lineHeight,
          letterSpacing: tokens.typography['label-lg'].letterSpacing,
        }],
        'label-md': [tokens.typography['label-md'].fontSize, {
          fontWeight: tokens.typography['label-md'].fontWeight,
          lineHeight: tokens.typography['label-md'].lineHeight,
        }],
        'label-sm': [tokens.typography['label-sm'].fontSize, {
          fontWeight: tokens.typography['label-sm'].fontWeight,
          lineHeight: tokens.typography['label-sm'].lineHeight,
          letterSpacing: tokens.typography['label-sm'].letterSpacing,
        }],
      },
      borderRadius: {
        sm: tokens.rounded.sm,
        md: tokens.rounded.md,
        lg: tokens.rounded.lg,
        xl: tokens.rounded.xl,
        full: tokens.rounded.full,
      },
      spacing: {
        unit: tokens.spacing.unit,
        xs: tokens.spacing.xs,
        sm: tokens.spacing.sm,
        md: tokens.spacing.md,
        lg: tokens.spacing.lg,
        xl: tokens.spacing.xl,
        xxl: tokens.spacing.xxl,
      },
      boxShadow: {
        '1': tokens.shadows['shadow-1'],
        '2': tokens.shadows['shadow-2'],
        '3': tokens.shadows['shadow-3'],
        '4': tokens.shadows['shadow-4'],
        '5': tokens.shadows['shadow-5'],
        'glow': tokens.shadows['shadow-glow'],
        'card': tokens.shadows['shadow-card'],
        'card-hover': tokens.shadows['shadow-card-hover'],
        'elevated': tokens.shadows['shadow-elevated'],
        'overlay': tokens.shadows['shadow-overlay'],
        'modal': tokens.shadows['shadow-modal'],
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'slide-left': 'slideLeft 0.3s ease-out',
        'slide-right': 'slideRight 0.3s ease-out',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
        'bounce-soft': 'bounceSoft 1s ease-in-out infinite',
        'spin-slow': 'spin 3s linear infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'float': 'float 3s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.97)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideLeft: {
          '0%': { opacity: '0', transform: 'translateX(-12px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideRight: {
          '0%': { opacity: '0', transform: 'translateX(12px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        bounceSoft: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-4px)' },
        },
      },
      transitionProperty: {
        'all': 'all',
        'bg': 'background-color',
        'border': 'border-color',
        'opacity': 'opacity',
        'transform': 'transform',
        'shadow': 'box-shadow',
      },
      transitionDuration: {
        'fast': '150ms',
        'normal': '200ms',
        'slow': '300ms',
      },
      transitionTimingFunction: {
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [],
};
